### ISSUE TITLE
sidecar container option

### ISSUE THREAD

**Issue by akshat87** [OpenLiberty/open-liberty-operator#103]
In open liberty helm chart, there was option to add extra container, it helped us create a container running file-beat for shipping application log files to out centralized logging.

**Comment by navidsh** [comment]
Hey @akshat87! Thanks for your feedback

**Comment by leochr** [comment]
@JusteenR At various places in the operator's code, the main container (with application image) is accessed using index. Example: 
```code
envList := pts.Spec.Containers[0].Env
```

That was fine because it was the only container. But with this sidecar container support, that's probably not alright. Perhaps, we should pick the container based on the name. But then need to ensure that the default container's name is not used by any of the sidecar containers.

**Comment by JusteenR** [comment]
This issue is being addressed at https://github.com/application-stacks/operator/issues/24

**Comment by leochr** [comment]
The sidecar container support is added in Open Liberty Operator 0.4.0. Now available in embedded Operators catalog in OpenShift as well as OperatorHub.io : https://operatorhub.io/operator/open-liberty

**Comment by akshat87** [comment]
thanks !
